include:
  - ./compose/docker-compose.it-tools.yaml
  - ./compose/docker-compose.monitoring.yaml
  - ./compose/docker-compose.portainer.yaml
  # - ./compose/docker-compose.sparky-fitness.yaml
  - ./compose/docker-compose.vert.yaml
  - ./compose/docker-compose.watchtower.yaml

services:

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: ${HOMEPAGE_NAME:-homepage}
    ports:
      - ${HOMEPAGE_PORT:-3030}:3000
    volumes:
      - ./rendered/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=gethomepage.dev,${HOMELAB_ADDRESS}:${HOMEPAGE_PORT},${HOMELAB_DOMAIN:-my.home.lab}:${HOMEPAGE_PORT}

