---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Виджеты:
    - Календарь:
        widget:
          type: calendar
          firstDayInWeek: monday
          view: monthly
          showTime: true
          timezone: Europe/Moscow

- Локальные сервисы:

    - VERT.sh:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/vert.svg
        href: http://{{ HOMELAB_ADDRESS }}:3333/
        description: Конвертация файлов

    - Grafana:
        icon: grafana.svg
        href: http://{{ HOMELAB_ADDRESS }}:3000/
        description: Grafana на локальном сервере
        widget:
          type: grafana
          url: http://{{ HOMELAB_ADDRESS }}:3000
          username: {{ GRAFANA_USER }}
          password: {{ GRAFANA_PASSWORD }}

    - Portainer:
        icon: portainer.svg
        href: http://{{ HOMELAB_ADDRESS }}:9000/
        description: Portainer на локальном сервере
        widget:
          type: portainer
          url: https://{{ HOMELAB_ADDRESS }}:9443
          env: {{ PORTAINER_ENV }}
          key: {{ PORTAINER_KEY }}

    - Tailscale:
        icon: tailscale.svg
        href: https://remote.routerich.ru/devices
        description: Управление Tailscale подключениями
        # widget:
        #   type: tailscale
        #   address: https://remote.routerich.ru/
        #   deviceid: routerich
        #   key: {{ TAILSCALE_KEY }}

- Дизайн:
    - VERT.sh:
        href: http://{{ HOMELAB_ADDRESS }}:3333
        description: Конвертация файлов

- Разработка:
    - VERT.sh:
        href: http://{{ HOMELAB_ADDRESS }}:3333
        description: Конвертация файлов
